name: notify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: notify
        uses: koki-develop/push-pocket-action@main
        with:
          slack-channel-id: "#feeds"
          slack-access-token: ${{ secrets.SLACK_ACCESS_TOKEN }}
          pocket-consumer-key: ${{ secrets.POCKET_CONSUMER_KEY }}
          pocket-access-token: ${{ secrets.POCKET_ACCESS_TOKEN }}
          count: 3
          archive: true
