name: pocket

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  pocket:
    runs-on: ubuntu-latest
    steps:
      - uses: koki-develop/push-pocket-action@v1.1.0
        with:
          slack-channel-id: "#feeds"
          slack-access-token: ${{ secrets.SLACK_ACCESS_TOKEN }}
          pocket-consumer-key: ${{ secrets.POCKET_CONSUMER_KEY }}
          pocket-access-token: ${{ secrets.POCKET_ACCESS_TOKEN }}
          count: 3
          archive: true
